import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  MediaController,
  MediaControlBar,
  MediaTimeRange,
  MediaTimeDisplay,
  MediaLoadingIndicator,
  MediaVolumeRange,
  MediaPlaybackRateButton,
  MediaPlayButton,
  MediaSeekBackwardButton,
  MediaSeekForwardButton,
  MediaMuteButton,
  MediaCaptionsButton,
  MediaAirplayButton,
  MediaPipButton,
  MediaFullscreenButton,
} from "media-chrome/dist/react";

const primaryColor = "white";
const chromeStyles = {
  "--media-icon-color": primaryColor,
  "--media-range-thumb-background": primaryColor,
  "--media-range-bar-color": primaryColor,
  color: primaryColor,
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Media Chrome React+Next.JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.media-chrome.org" target="_blank">Media Chrome!</a>
        </h1>
        <MediaController
          ref={(node: HTMLElement) => console.log("ref", node)}
          style={chromeStyles}
        >
          <video
            slot="media"
            src="https://stream.mux.com/DS00Spx1CV902MCtPj5WknGlR102V5HFkDe/high.mp4"
            preload="auto"
            muted
            crossOrigin=""
          >
            <track
              label="thumbnails"
              default
              kind="metadata"
              src="https://image.mux.com/DS00Spx1CV902MCtPj5WknGlR102V5HFkDe/storyboard.vtt"
            />
            <track
              label="English"
              kind="captions"
              srcLang="en"
              src="./vtt/en-cc.vtt"
            />
          </video>
          <div slot="centered-chrome" no-auto-hide="">
            <MediaLoadingIndicator
              style={{ "--media-loading-icon-width": 80 }}
            ></MediaLoadingIndicator>
          </div>
          <MediaControlBar>
            <MediaPlayButton></MediaPlayButton>
            <MediaSeekBackwardButton></MediaSeekBackwardButton>
            <MediaSeekForwardButton></MediaSeekForwardButton>
            <MediaTimeRange></MediaTimeRange>
            <MediaTimeDisplay showDuration></MediaTimeDisplay>
            <MediaMuteButton></MediaMuteButton>
            <MediaVolumeRange></MediaVolumeRange>
            <MediaPlaybackRateButton></MediaPlaybackRateButton>
            <MediaCaptionsButton defaultShowing></MediaCaptionsButton>
            <MediaAirplayButton></MediaAirplayButton>
            <MediaPipButton></MediaPipButton>
            <MediaFullscreenButton></MediaFullscreenButton>
          </MediaControlBar>
        </MediaController>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
