import Head from 'next/head';
import styles from './styles.module.css';
import { Player } from './player';

export default function Page() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Media Chrome React+Next.JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <a
            href="https://www.media-chrome.org"
            target="_blank"
            rel="noreferrer"
          >
            Media Chrome!
          </a>
        </h1>
        <Player />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
